FROM node:alpine

#ARG로 변수 선언
ARG TYPEORM_HOST
ARG TYPEORM_PORT
ARG TYPEORM_USERNAME
ARG TYPEORM_PASSWORD
ARG TYPEORM_DATABASE
ARG TYPEORM_SYNCHRONIZE
ARG TYPEORM_LOGGING
ARG JWT_SECRET

ENV TYPEORM_HOST=$TYPEORM_HOST \
TYPEORM_PORT=$TYPEORM_PORT \
TYPEORM_USERNAME=$TYPEORM_USERNAME \
TYPEORM_PASSWORD=$TYPEORM_PASSWORD \
TYPEORM_DATABASE=$TYPEORM_DATABASE \
TYPEORM_SYNCHRONIZE=$TYPEORM_SYNCHRONIZE \
TYPEORM_LOGGING=$TYPEORM_LOGGING \
JWT_SECRET=$JWT_SECRET

LABEL creator="soi@dev_camp"
WORKDIR /app 
COPY . .
COPY package.json .
COPY package-lock.json .
RUN npm install
RUN npm run build
CMD ["node", "dist/main"]
