name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Enable APIs
        run: |
          gcloud services enable run.googleapis.com \
            artifactregistry.googleapis.com \
            --project=${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjs-app:$GITHUB_SHA \
            --build-arg TYPEORM_HOST=${{ secrets.TYPEORM_HOST }} \
            --build-arg TYPEORM_PORT=${{ secrets.TYPEORM_PORT }} \
            --build-arg TYPEORM_USERNAME=${{ secrets.TYPEORM_USERNAME }} \
            --build-arg TYPEORM_PASSWORD=${{ secrets.TYPEORM_PASSWORD }} \
            --build-arg TYPEORM_DATABASE=${{ secrets.TYPEORM_DATABASE }} \
            --build-arg TYPEORM_SYNCHRONIZE=${{ secrets.TYPEORM_SYNCHRONIZE }} \
            --build-arg TYPEORM_LOGGING=${{ secrets.TYPEORM_LOGGING }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjs-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nestjs-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjs-app:$GITHUB_SHA \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars PORT=3000